name: Build on DockerHub and Deploy to AWS
on:
  push:
    branches:
      - main
env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          dockerfile: ./Dockerfile   # Specify the path to your Dockerfile here
          tags: ashokpoudel/cddemo:latest
  deploy:
    needs: build  # Specifies that the `deploy` job depends on the `build` job
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_TOKEN }}

    - name: Pull Docker image
      run: |
        ssh -i ${{ secrets.AWS_PRIVATE_KEY }} ubuntu@3.86.140.155s 'sudo docker pull ashokpoudel/cddemo:latest'

    - name: Stop running container
      run: |
        ssh -i ${{ secrets.AWS_PRIVATE_KEY }} ubuntu@3.86.140.155s 'sudo docker stop cddemo || true'
        ssh -i ${{ secrets.AWS_PRIVATE_KEY }} ubuntu@3.86.140.155s 'sudo docker rm cddemo || true'

    - name: Run new container
      run: |
        ssh -i ${{ secrets.AWS_PRIVATE_KEY }} ubuntu@3.86.140.155s 'sudo docker run -d --name cddemo -p 80:80 ashokpoudel/cddemo:latest'