name: Deploy to Heroku
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          dockerfile: ./Dockerfile   # Specify the path to your Dockerfile here
          tags: ashokpoudel/cddemo:latest
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull Docker image
      run: |
        ssh -i cesecret.pem ubuntu@3.86.140.155s 'sudo docker pull ashokpoudel/cddemo:latest'

    - name: Stop running container
      run: |
        ssh -i cesecret.pem ubuntu@3.86.140.155s 'sudo docker stop cddemo || true'
        ssh -i cesecret.pem ubuntu@3.86.140.155s 'sudo docker rm cddemo || true'

    - name: Run new container
      run: |
        ssh -i cesecret.pem ubuntu@3.86.140.155s 'sudo docker run -d --name cddemo -p 80:80 ashokpoudel/cddemo:latest'